# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files in Repo
        run: |
          echo "Listing files in $(pwd)"
          ls -al
          echo " can run TF validate, plan, apply, etc."
      
