# .github/workflows/caller-workflow.yml
name: Call Reusable Workflow
#on action
on:
  push:
    branches:
      - main  # or your branch name
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-workflow.yml
